/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jutils_jprocesses_jni_ProcessesDataCollector */

#ifndef _Included_org_jutils_jprocesses_jni_ProcessesDataCollector
#define _Included_org_jutils_jprocesses_jni_ProcessesDataCollector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jutils_jprocesses_jni_ProcessesDataCollector
 * Method:    getProcessesData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jutils_jprocesses_jni_ProcessesDataCollector_getProcessesData
  (JNIEnv *, jobject);

/*
 * Class:     org_jutils_jprocesses_jni_ProcessesDataCollector
 * Method:    killProcess
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jutils_jprocesses_jni_ProcessesDataCollector_killProcess
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
